# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x04\x63hat\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\x0eServerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0funread_messages\x18\x03 \x01(\x05\"\x1e\n\x0bListRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\"\x1d\n\x08UserList\x12\x11\n\tusernames\x18\x01 \x03(\t\"T\n\x0b\x43hatRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"U\n\x0c\x43hatResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"/\n\x0c\x46\x65tchRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"6\n\rDeleteRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0bmessage_ids\x18\x02 \x03(\x05\x32\x9c\x03\n\x0b\x43hatService\x12\x37\n\x08Register\x12\x15.chat.UserCredentials\x1a\x14.chat.ServerResponse\x12\x33\n\x05Login\x12\x15.chat.UserCredentials\x1a\x13.chat.LoginResponse\x12\x31\n\x0cListAccounts\x12\x11.chat.ListRequest\x1a\x0e.chat.UserList\x12\x36\n\x0bSendMessage\x12\x11.chat.ChatRequest\x1a\x14.chat.ServerResponse\x12\x39\n\rFetchMessages\x12\x12.chat.FetchRequest\x1a\x12.chat.ChatResponse0\x01\x12;\n\x0e\x44\x65leteMessages\x12\x13.chat.DeleteRequest\x1a\x14.chat.ServerResponse\x12<\n\rDeleteAccount\x12\x15.chat.UserCredentials\x1a\x14.chat.ServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERCREDENTIALS']._serialized_start=24
  _globals['_USERCREDENTIALS']._serialized_end=77
  _globals['_SERVERRESPONSE']._serialized_start=79
  _globals['_SERVERRESPONSE']._serialized_end=128
  _globals['_LOGINRESPONSE']._serialized_start=130
  _globals['_LOGINRESPONSE']._serialized_end=203
  _globals['_LISTREQUEST']._serialized_start=205
  _globals['_LISTREQUEST']._serialized_end=235
  _globals['_USERLIST']._serialized_start=237
  _globals['_USERLIST']._serialized_end=266
  _globals['_CHATREQUEST']._serialized_start=268
  _globals['_CHATREQUEST']._serialized_end=352
  _globals['_CHATRESPONSE']._serialized_start=354
  _globals['_CHATRESPONSE']._serialized_end=439
  _globals['_FETCHREQUEST']._serialized_start=441
  _globals['_FETCHREQUEST']._serialized_end=488
  _globals['_DELETEREQUEST']._serialized_start=490
  _globals['_DELETEREQUEST']._serialized_end=544
  _globals['_CHATSERVICE']._serialized_start=547
  _globals['_CHATSERVICE']._serialized_end=959
# @@protoc_insertion_point(module_scope)
